### ISSUE TITLE
Fail to run demo due to missing data files

### ISSUE THREAD

**Issue by raxxerwan** [QianliM/CAPE#7]
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    reference_mesh_file=reference_mesh_file)
  File "/home/xxx/CAPE/lib/load_data.py", line 51, in __init__
    self.load()
  File "/home/xxx/CAPE/lib/load_data.py", line 62, in load
    vertices_train = np.load(self.train_mesh_fn)
  File "/home/xxx/anaconda3/envs/tf1.13/lib/python3.6/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxx/CAPE/data/datasets/dataset_male_4clotypes/train/train_disp.npy'

How can I fix this? Thx!

**Comment by QianliM** [comment]
H
